.PHONY: clean

scheme: scheme.c models.c util.c eval.c write.c read.c io.c environment.c
	  gcc -Wall -ansi -o scheme scheme.c models.c util.c eval.c write.c read.c io.c environment.c
	  
clean:
	  rm scheme